In [4]:
import os
import pandas as pd
import re

In [5]:
import kagglehub
from kagglehub import KaggleDatasetAdapter

file_path = "IMDB Dataset.csv"
df = kagglehub.dataset_load(
  KaggleDatasetAdapter.PANDAS,
  "lakshmi25npathi/imdb-dataset-of-50k-movie-reviews",
  file_path,
)

Using Colab cache for faster access to the 'imdb-dataset-of-50k-movie-reviews' dataset.

In [6]:
df.shape

(50000, 2)

In [7]:
df.describe()

                                                   review sentiment
count                                               50000     50000
unique                                              49582         2
top     Loved today's show!!! It was a variety and not...  positive
freq                                                    5     25000

In [8]:
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [9]:
df['review'].str.lower()

0        one of the other reviewers has mentioned that ...
1        a wonderful little production. <br /><br />the...
2        i thought this was a wonderful way to spend ti...
3        basically there's a family where a little boy ...
4        petter mattei's "love in the time of money" is...
                               ...
49995    i thought this movie did a down right good job...
49996    bad plot, bad dialogue, bad acting, idiotic di...
49997    i am a catholic taught in parochial elementary...
49998    i'm going to have to disagree with the previou...
49999    no one expects the star trek movies to be high...
Name: review, Length: 50000, dtype: object

In [10]:
df["review"][0].lower()

"one of the other reviewers has mentioned that after watching just 1 oz episode you'll be hooked. they are right, as this is exactly what happened with me.<br /><br />the first thing that struck me about oz was its brutality and unflinching scenes of violence, which set in right from the word go. trust me, this is not a show for the faint hearted or timid. this show pulls no punches with regards to drugs, sex or violence. its is hardcore, in the classic use of the word.<br /><br />it is called oz as that is the nickname given to the oswald maximum security state penitentary. it focuses mainly on emerald city, an experimental section of the prison where all the cells have glass fronts and face inwards, so privacy is not high on the agenda. em city is home to many..aryans, muslims, gangstas, latinos, christians, italians, irish and more....so scuffles, death stares, dodgy dealings and shady agreements are never far away.<br /><br />i would say the main appeal of the show is due to the fact that it goes where other shows wouldn't dare. forget pretty pictures painted for mainstream audiences, forget charm, forget romance...oz doesn't mess around. the first episode i ever saw struck me as so nasty it was surreal, i couldn't say i was ready for it, but as i watched more, i developed a taste for oz, and got accustomed to the high levels of graphic violence. not just violence, but injustice (crooked guards who'll be sold out for a nickel, inmates who'll kill on order and get away with it, well mannered, middle class inmates being turned into prison bitches due to their lack of street skills or prison experience) watching oz, you may become comfortable with what is uncomfortable viewing....thats if you can get in touch with your darker side."

# Removal of HTML Tags

In [11]:
def tag_removal(text):
    pattern=re.compile('<.*?>')
    return pattern.sub(r'',text)

In [12]:
clean_text=tag_removal(df['review'][0])
clean_text

"One of the other reviewers has mentioned that after watching just 1 Oz episode you'll be hooked. They are right, as this is exactly what happened with me.The first thing that struck me about Oz was its brutality and unflinching scenes of violence, which set in right from the word GO. Trust me, this is not a show for the faint hearted or timid. This show pulls no punches with regards to drugs, sex or violence. Its is hardcore, in the classic use of the word.It is called OZ as that is the nickname given to the Oswald Maximum Security State Penitentary. It focuses mainly on Emerald City, an experimental section of the prison where all the cells have glass fronts and face inwards, so privacy is not high on the agenda. Em City is home to many..Aryans, Muslims, gangstas, Latinos, Christians, Italians, Irish and more....so scuffles, death stares, dodgy dealings and shady agreements are never far away.I would say the main appeal of the show is due to the fact that it goes where other shows wouldn't dare. Forget pretty pictures painted for mainstream audiences, forget charm, forget romance...OZ doesn't mess around. The first episode I ever saw struck me as so nasty it was surreal, I couldn't say I was ready for it, but as I watched more, I developed a taste for Oz, and got accustomed to the high levels of graphic violence. Not just violence, but injustice (crooked guards who'll be sold out for a nickel, inmates who'll kill on order and get away with it, well mannered, middle class inmates being turned into prison bitches due to their lack of street skills or prison experience) Watching Oz, you may become comfortable with what is uncomfortable viewing....thats if you can get in touch with your darker side."

In [13]:
df["review"] = df["review"].apply(tag_removal)

In [14]:
df["review"][1]

'A wonderful little production. The filming technique is very unassuming- very old-time-BBC fashion and gives a comforting, and sometimes discomforting, sense of realism to the entire piece. The actors are extremely well chosen- Michael Sheen not only "has got all the polari" but he has all the voices down pat too! You can truly see the seamless editing guided by the references to Williams\' diary entries, not only is it well worth the watching but it is a terrificly written and performed piece. A masterful production about one of the great master\'s of comedy and his life. The realism really comes home with the little things: the fantasy of the guard which, rather than use the traditional \'dream\' techniques remains solid then disappears. It plays on our knowledge and our senses, particularly with the scenes concerning Orton and Halliwell and the sets (particularly of their flat with Halliwell\'s murals decorating every surface) are terribly well done.'

# Removal of URLs

In [15]:
text1="My name is suman kar my portfolio link is : https://portfolio-website-beta-six-63.vercel.app/"
text=re.sub(r'http\S+', '', text1)
text

'My name is suman kar my portfolio link is : '

# Removing punctuation

In [16]:
import string
exclude= string.punctuation
exclude

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [17]:
def remove_punc(text):
  for char in exclude:
    text=text.replace(char,'')
  text=re.sub('[0-9]+','',text)
  return text

In [18]:
df["review"][1]

'A wonderful little production. The filming technique is very unassuming- very old-time-BBC fashion and gives a comforting, and sometimes discomforting, sense of realism to the entire piece. The actors are extremely well chosen- Michael Sheen not only "has got all the polari" but he has all the voices down pat too! You can truly see the seamless editing guided by the references to Williams\' diary entries, not only is it well worth the watching but it is a terrificly written and performed piece. A masterful production about one of the great master\'s of comedy and his life. The realism really comes home with the little things: the fantasy of the guard which, rather than use the traditional \'dream\' techniques remains solid then disappears. It plays on our knowledge and our senses, particularly with the scenes concerning Orton and Halliwell and the sets (particularly of their flat with Halliwell\'s murals decorating every surface) are terribly well done.'

In [19]:
remove_punc(df["review"][1])

'A wonderful little production The filming technique is very unassuming very oldtimeBBC fashion and gives a comforting and sometimes discomforting sense of realism to the entire piece The actors are extremely well chosen Michael Sheen not only has got all the polari but he has all the voices down pat too You can truly see the seamless editing guided by the references to Williams diary entries not only is it well worth the watching but it is a terrificly written and performed piece A masterful production about one of the great masters of comedy and his life The realism really comes home with the little things the fantasy of the guard which rather than use the traditional dream techniques remains solid then disappears It plays on our knowledge and our senses particularly with the scenes concerning Orton and Halliwell and the sets particularly of their flat with Halliwells murals decorating every surface are terribly well done'

In [20]:
import time

start=time.time()
df["review"]=df["review"].apply(remove_punc)
end=time.time()
print(end-start)

2.963613271713257

In [22]:
from textblob import TextBlob

In [28]:
incorrect_text="iam suman kaer im domng bthc im zCse"

In [29]:
text_blb=TextBlob(incorrect_text)
text_blb.correct().string

'am human her in doing the in case'

In [32]:
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords

stopwords.words('english')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

['a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 "he'd",
 "he'll",
 'her',
 'here',
 'hers',
 'herself',
 "he's",
 'him',
 'himself',
 'his',
 'how',
 'i',
 "i'd",
 'if',
 "i'll",
 "i'm",
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it'd",
 "it'll",
 "it's",
 'its',
 'itself',
 "i've",
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 're',
 's',
 'same',
 'shan',
 "shan't",
 'she',
 "she'd",
 "she'll",
 "she's",
 'should',
 'shouldn',
 "shouldn't",
 "should've",
 'so',
 'some',
 'such',
 't',
 'than',
 'that',
 "that'll",
 'the',
 'their',
 'theirs',
 'them',
 'themselves',
 'then',
 'there',
 'these',
 'they',
 "they'd",
 "they'll",
 "they're",
 "they've",
 'this',
 'those',
 'through',
 'to',
 'too',
 'under',
 'until',
 'up',
 've',
 'very',
 'was',
 'wasn',
 "wasn't",
 'we',
 "we'd",
 "we'll",
 "we're",
 'were',
 'weren',
 "weren't",
 "we've",
 'what',
 'when',
 'where',
 'which',
 'while',
 'who',
 'whom',
 'why',
 'will',
 'with',
 'won',
 "won't",
 'wouldn',
 "wouldn't",
 'y',
 'you',
 "you'd",
 "you'll",
 'your',
 "you're",
 'yours',
 'yourself',
 'yourselves',
 "you've"]

In [49]:
def remove_stopword(text):
  new_text=[]


  for words in text.split():
    if words in stopwords.words('english'):
      new_text.append('')
    else:
      new_text.append(words)


  x=new_text[:]
  new_text.clear()
  return " ".join(x)

In [50]:
remove_stopword(df['review'][0])

'One    reviewers  mentioned   watching  Oz episode youll  hooked They  right    exactly  happened  meThe first thing  struck   Oz   brutality  unflinching scenes  violence  set  right   word GO Trust      show   faint hearted  timid This show pulls  punches  regards  drugs sex  violence Its  hardcore   classic use   wordIt  called OZ     nickname given   Oswald Maximum Security State Penitentary It focuses mainly  Emerald City  experimental section   prison    cells  glass fronts  face inwards  privacy   high   agenda Em City  home  manyAryans Muslims gangstas Latinos Christians Italians Irish  moreso scuffles death stares dodgy dealings  shady agreements  never far awayI would say  main appeal   show  due   fact   goes   shows wouldnt dare Forget pretty pictures painted  mainstream audiences forget charm forget romanceOZ doesnt mess around The first episode I ever saw struck    nasty   surreal I couldnt say I  ready     I watched  I developed  taste  Oz  got accustomed   high levels  graphic violence Not  violence  injustice crooked guards wholl  sold    nickel inmates wholl kill  order  get away   well mannered middle class inmates  turned  prison bitches due   lack  street skills  prison experience Watching Oz  may become comfortable    uncomfortable viewingthats    get  touch   darker side'

In [54]:
!pip install emoji

Collecting emoji
  Downloading emoji-2.15.0-py3-none-any.whl.metadata (5.7 kB)
Downloading emoji-2.15.0-py3-none-any.whl (608 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 608.4/608.4 kB 40.4 MB/s eta 0:00:00
Installing collected packages: emoji
Successfully installed emoji-2.15.0

In [55]:
import emoji

In [58]:
text="Don't you 🥺 love me?"

In [59]:
emoji.demojize(text)

"Don't you :pleading_face: love me?"

# Tokenization

In [64]:
sent1=df["review"][1]
sent1.split()

['A',
 'wonderful',
 'little',
 'production',
 'The',
 'filming',
 'technique',
 'is',
 'very',
 'unassuming',
 'very',
 'oldtimeBBC',
 'fashion',
 'and',
 'gives',
 'a',
 'comforting',
 'and',
 'sometimes',
 'discomforting',
 'sense',
 'of',
 'realism',
 'to',
 'the',
 'entire',
 'piece',
 'The',
 'actors',
 'are',
 'extremely',
 'well',
 'chosen',
 'Michael',
 'Sheen',
 'not',
 'only',
 'has',
 'got',
 'all',
 'the',
 'polari',
 'but',
 'he',
 'has',
 'all',
 'the',
 'voices',
 'down',
 'pat',
 'too',
 'You',
 'can',
 'truly',
 'see',
 'the',
 'seamless',
 'editing',
 'guided',
 'by',
 'the',
 'references',
 'to',
 'Williams',
 'diary',
 'entries',
 'not',
 'only',
 'is',
 'it',
 'well',
 'worth',
 'the',
 'watching',
 'but',
 'it',
 'is',
 'a',
 'terrificly',
 'written',
 'and',
 'performed',
 'piece',
 'A',
 'masterful',
 'production',
 'about',
 'one',
 'of',
 'the',
 'great',
 'masters',
 'of',
 'comedy',
 'and',
 'his',
 'life',
 'The',
 'realism',
 'really',
 'comes',
 'home',
 'with',
 'the',
 'little',
 'things',
 'the',
 'fantasy',
 'of',
 'the',
 'guard',
 'which',
 'rather',
 'than',
 'use',
 'the',
 'traditional',
 'dream',
 'techniques',
 'remains',
 'solid',
 'then',
 'disappears',
 'It',
 'plays',
 'on',
 'our',
 'knowledge',
 'and',
 'our',
 'senses',
 'particularly',
 'with',
 'the',
 'scenes',
 'concerning',
 'Orton',
 'and',
 'Halliwell',
 'and',
 'the',
 'sets',
 'particularly',
 'of',
 'their',
 'flat',
 'with',
 'Halliwells',
 'murals',
 'decorating',
 'every',
 'surface',
 'are',
 'terribly',
 'well',
 'done']

In [68]:
sent2="I am a student? i study computer science? i have good knowledge in Ai"
sent2.split('?')

['I am a student', ' i study computer science', ' i have good knowledge in Ai']

In [69]:
from nltk.tokenize import word_tokenize,sent_tokenize

In [74]:
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

True

In [75]:
sent4="I am a student? i study computer science, i have good knowledge in Ai. thankyou"
word_tokenize(sent4)

['I',
 'am',
 'a',
 'student',
 '?',
 'i',
 'study',
 'computer',
 'science',
 ',',
 'i',
 'have',
 'good',
 'knowledge',
 'in',
 'Ai',
 '.',
 'thankyou']

In [76]:
sent_tokenize(sent4)

['I am a student?',
 'i study computer science, i have good knowledge in Ai.',
 'thankyou']

In [77]:
import spacy

In [82]:
nlp=spacy.load("en_core_web_sm")

In [84]:
doc1=nlp(sent4)
for token in doc1:
  print(token)

I
am
a
student
?
i
study
computer
science
,
i
have
good
knowledge
in
Ai
.
thankyou

# Stemming

In [85]:
from nltk.stem.porter import PorterStemmer

In [93]:
ps=PorterStemmer()

def stem_words(text):
  return " ".join([ps.stem(word) for word in text.split()])

In [96]:
sample="like liking liked"

In [97]:
stem_words(sample)

'like like like'

In [98]:
stem_words(sent4)

'i am a student? i studi comput science, i have good knowledg in ai. thankyou'

# Lemmatization

In [100]:
from nltk.stem import WordNetLemmatizer
wl=WordNetLemmatizer()

In [101]:
sentence="One of the other reviewers has mentioned that after watching just 1 Oz episode you'll be hooked."

In [110]:
import nltk
nltk.download('wordnet')

punc = string.punctuation
sentence_token = word_tokenize(sentence)
cleaned_sentence_token = [word for word in sentence_token if word not in punc]


print("{0:20}{1:20}".format('Word','Lemma'))
for words in cleaned_sentence_token:
  print("{0:20}{1:20}".format(words, wl.lemmatize(words, pos='v')))# verb

Word                Lemma
One                 One
of                  of
the                 the
other               other
reviewers           reviewers
has                 have
mentioned           mention
that                that
after               after
watching            watch
just                just
1                   1
Oz                  Oz
episode             episode
you                 you
'll                 'll
be                  be
hooked              hook

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!